Bookstore: Add api features
mateo951/bookstore pull request #3
Opened 2021-10-06 22:31 UTC by mateo951

- Added add-remove functionality with API connectivity
- Added linters checks

2021-10-06 23:16 UTC, barackm requested changes
Hi @mateo951, 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

# STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 
![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 23:16 UTC, barackm commented on src/redux/books/books.js
>    }
- [ ] You have done a great job so far, but I think we can still improve your code, for now, the way you are using the thunk creators and dispatching actions is not the right way. let me try to explain:
- The reducer is a pure function so it does not need to deal with side effects like calling APIs, but for now, your reducer is calling two functions that are dealing with API calls `postBook(action.payload); and deleteBook(action.payload);`
- The right flow we need to follow while working with APIs in redux is this one: when we click on the submit button from the form, we should dispatch an action that should be a thunk, this is where we will then have to call the API, then after receiving the response we will dispatch another type of action that will be caught by the reducer and then update the state. Ex: If we need to load all the books from the server and update the state, This can be something like this: 
```
// Action types
const ADD_BOOK = 'bookStore/books/ADD_BOOK';
const REMOVE_BOOK = 'bookStore/books/REMOVE_BOOK';
const GET_BOOKS = 'bookStore/books/GET_BOOKS';
const apiURL = 'https://us-central1-bookstore-api-e63c8.cloudfunctions.net/bookstoreApi/apps/MAmyp1rEJRIDJCjdo3Id/books';

// Action creators
const getBooks = (books) => ({
    action: GET_BOOKS,
    payload: books,
)};
const addBook = (book) => ({
    action: ADD_BOOK,
    payload: book,
)};
const removeBook = (bookId) => ({
    action: REMOVE_BOOK,
    payload: bookId,
)};

// thunk creators

export const getBooksAsync = (book) => async (dispatch) => {
  try{
      const response = await axios.get(apiURL)
      dispatch(getBooks(response.data));
  }catch(ex) {
      // dispatch an action for the failling scenario
   }
}

// reducer
const reducer = (state = initialState, action) => {
  let newArr = [];
  switch (action.type) {
    case GET_BOOKS:
      newArr = action.payload.slice();
      return { ...state, books: newArr };
    case ADD_BOOK:
      newArr = [...state.books, action.payload];
      return { ...state, books: newArr };
   // other cases
  }
};

```
With this, you will only need to dispatch the action `getBooksAsync` from the react components to load all the books and the reducer will no longer call functions that deal with API calls. You can now add other thunk creators for adding a book and removing a book (`addBookAsync, removeBookAsync`). 😉

2021-10-06 23:40 UTC, mateo951 commented on src/redux/books/books.js
>    }
One of the best, if not the best review I've had in Microverse! Thanks for this awesome feedback and actually taking your time to explain concepts plus why you request a change! Your explanation was super clear and now I understand why reducers should be pure! Keep rocking @barackm

2021-10-06 23:45 UTC, barackm commented on src/redux/books/books.js
>    }
Thank you @mateo951, I appreciate it! ❤️

2021-10-07 08:19 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @mateo951,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-07 14:29 UTC, merged